WebUI/Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Domain.Entities;
using Domain.ModelView;
using Domain.Repository;

namespace WebUI.Controllers
{
    public class OrdersController : BaseController
    {
        OrderRepository repo = new OrderRepository();
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.MenuItem = "orders";
            List<OrderView> order = repo.GetOrders(Cust.ID_CUSTOM);
            return View(order);
        }

        public async Task<ActionResult> Create()
        {
            OrderV order = await repo.GetCreate(Cust.ID_CUSTOM);
            SetCookie("OrderId", order.Order.OrderId);
            return RedirectToAction("GoodSelect");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OrderV order, string Gd)
        {
            if (ModelState.IsValid)
            {
                if (Gd != null)
                {
                    return RedirectToAction("GoodSelect");
                }

                return RedirectToAction("Index");
            }

            return View(order);
        }

        public ActionResult DelProducts(int id)
        {
            OrderProductView good = db.OrderProductViews.Find(id);
            return View(good);
        }

        [HttpPost]
        public ActionResult DelProducts(OrderProductView ord,int id)
        {
            OrderProduct prod = db.OrderProducts.Find(id);
            db.OrderProducts.Remove(prod);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Copy(int id)
        {
            OrderV ord = repo.GetCopy(id);
            SetCookie("OrderId", ord.Order.OrderId);
            return View("Details", ord);
        }

        public ActionResult GoodSelect()
        {
            int ord = GetIntCookie("OrderId");
            List<GoodSelect> goods = repo.GetGood(ord);
            return View(goods);
        }

        public ActionResult Details(int id,decimal qty)
        {
            int ord = GetIntCookie("OrderId");
            OrderProduct prod = new OrderProduct();
            prod.Quant = qty;
            prod.ProductId = id;
            prod.OrderId = ord;
            db.OrderProducts.Add(prod);
            db.SaveChanges();
            OrderV order = repo.GetOrderV(ord);
            return View(order);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Booking(OrderV ord, string Gd, int? ProductId, decimal qty, string Recalc)
        {
            if (Gd != null)
                return RedirectToAction("GoodSelect");
            if (Recalc != null)
            {
                OrderProduct good = db.OrderProducts.Find(ProductId);
                good.Quant = qty;
                db.Entry(good).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit");
            }
            ord.Order.CustId = Cust.ID_CUSTOM;
            repo.Save(ord);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? id)
        {
            OrderView order;
            if (id == null)
            {
                int orderid = GetIntCookie("OrderId");
                order = db.OrderViews.Find(orderid);
            }
            else
            {
                order = db.OrderViews.Find(id);    
            }
            
            if (order == null)
            {
                return HttpNotFound();
            }
            OrderV ord = new OrderV();
            ord.Order = order;
            ord.Prod = db.OrderProductViews.Where(p => p.OrderId == ord.Order.OrderId).ToList();
            return View("Details", ord);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,CustId,AdresId,Centr,Dat,note,insDate,StatusId")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View("Details",order);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OrderView order = db.OrderViews.Find(id);
            OrderV ord = new OrderV();
            ord.Order = order;
            ord.Prod = db.OrderProductViews.Where(p => p.OrderId == ord.Order.OrderId).ToList();
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(ord);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebUI/Views/Orders/AddProd.cshtml
@model IEnumerable<Domain.Entities.OrderProduct>

@{
    ViewBag.Title = "AddProd";
}

<h2>AddProd</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GoodId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quant)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GoodId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quant)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.OrderProductId }) |
            @Html.ActionLink("Details", "Details", new { id=item.OrderProductId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.OrderProductId })
        </td>
    </tr>
}

</table>

WebUI/Views/Orders/ChProducts.cshtml
@model Domain.Entities.OrderProductView

@{
    ViewBag.Title = "Изиенение";
}

<h2>Изиенение продукции</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.Good, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Good, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Good, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Unit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quant, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quant, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quant, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("К списку", "Index")
</div>

WebUI/Views/Orders/Create.cshtml
@model Domain.ModelView.OrderV
@{
    ViewBag.Title = "Новый заказ";
}
@*@section metatags
{
    <meta name="description" content="@ViewBag.Title" />
    <meta name="keywords" content="@ViewBag.Title, АБЗ-4" />
    <meta name="robots" content="noindex, nofollow">
}*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Styles.Render("~/Content/datetimepickercss")
    @Scripts.Render("~/bundles/datetimepickerjs")
}
<div class="row">
    <div class="col-md-12">
        <section id="orderForm" class="client-form">
            @using (Html.BeginForm("Create", "Orders", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <fieldset>
                    @Html.HiddenFor(model => model.Order.OrderId)
                    @Html.HiddenFor(model => model.Order.CustId)
                </fieldset>
                <h2>Заказанные товары</h2>
                <p align="center">
                    <input class="actionButtons btn btn-xs-sm-md btn-success" name="Gd" type="submit" value="Добавить товар" />
                </p>
                
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-grey-header null-margin">
                        <thead>
                            <tr>
                                <th>
                                    Продукция
                                </th>
                                <th>
                                    Ед. изм.
                                </th>
                                <th>
                                    Количество
                                </th>
                                <th>
                                    Управление
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Prod)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Good)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Unit)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Quant)
                                    </td>
                                    <td>
                                        @*@Html.ActionLink(HttpUtility.HtmlDecode("&#xe065;"), "ChDetail", new { id = item.OrderDetailId, act = "Edit" }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Редактировать товар" })
                                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe020;"), "DelDetail", new { id = item.OrderDetailId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Удалить товар" })*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                <h2>Выберите дату</h2>
                <div class="form-group">
                    @Html.LabelFor(m => m.Order.Dat, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Order.cDat, new { @class = "form-control datefield", @type = "text" })
                        @Html.ValidationMessageFor(m => m.Order.cDat, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr />
                <h2>Способ получения</h2>
                @*<div class="form-group">
                        @Html.LabelFor(model => model.Centr, htmlAttributes: new { @class = "col-md-3 control-label" })
                        <div class="col-md-9">
                            @Html.CheckBoxFor(model => model.Centr, new { @class = "form-control checkbox" })
                            @Html.ValidationMessageFor(model => model.Centr, "", new { @class = "text-danger" })
                        </div>
                    </div>*@
                <div class="form-group">
                    @Html.LabelFor(model => model.Order.Adres, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @*@Html.DropDownListFor(model => model.Order.AdresId, Model.SelectAdres, new { @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.Order.Adres, "", new { @class = "text-danger" })
                        <p class="help-block">
                            <input name="Adr" type="submit" value="@HttpUtility.HtmlDecode("&#xe081;")" class="glyphicon actionButtons btn btn-xs-sm-md btn-default glyph-btn" role="button" title="Внести новый адрес" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* Если вы хотите что бы доставку осуществил АБЗ-4
                            выберите из списка адрес доставки или внесите новый. Иначе выберите Самовывоз.
                        </p>
                    </div>
                </div>
                <hr />
                <hr />
                <h2>Дополнительная информация к заказу</h2>
                <div class="form-group">
                    @Html.LabelFor(model => model.Order.Note, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Order.Note, new { @class = "form-control multi-line", @rows = "3" })
                        @Html.ValidationMessageFor(model => model.Order.Note, "", new { @class = "text-danger" })
                        <p class="help-block">* тут вы можете указать удобное для вас время доставки продукции и другие ваши пожелания</p>
                    </div>
                </div>
                <p>&nbsp;</p>
                <p align="center">
                    <input class="actionButtons btn btn-xs-sm-md btn-success" type="submit" value="Сохранить заказ" />
                </p>
            }
            <hr />
            <div>
                @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к списку заказов", "Index", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к списку заказов" })
            </div>
        </section>
    </div>
</div>
@*<script type="text/javascript">
    $(function () {
        $('#Dat').datetimepicker({
            locale: 'ru', format: 'DD.MM.YYYY'
        });
    });
</script>*@

WebUI/Views/Orders/DelProducts.cshtml
@model Domain.Entities.OrderProductView

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление продукции</h2>

<h3>Вы уверены что хотите удалить эту продукцию из заказа?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Good)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Good)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quant)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К списку", "Index")
        </div>
    }
</div>

WebUI/Views/Orders/Delete.cshtml
@model Domain.ModelView.OrderV
@{
    ViewBag.Title = "Удаление";
}
<h2>Удаление заказа</h2>
<h3>Вы уверены что хотите удалить этот заказ?</h3>
<div>
    <fieldset>
        @Html.HiddenFor(model => model.Order.OrderId)
    </fieldset>
    <h2>Дата</h2>
    <div class="form-group">
        <div class="col-md-9">
            @Html.DisplayFor(m => m.Order.cDat)
        </div>
    </div>
    <h2>Заказанные товары</h2>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-grey-header null-margin">
            <thead>
                <tr>
                    <th>
                        Продукция
                    </th>
                    <th>
                        Ед. изм.
                    </th>
                    <th>
                        Количество
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Prod)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => item.Good)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Unit)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.Quant)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        
        <h2>Дополнительная информация к заказу</h2>
        <div class="form-group">
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Order.Note, new { @class = "form-control multi-line", @rows = "3" })
                @Html.ValidationMessageFor(model => model.Order.Note, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("К списку заказов", "Index")
        </div>
    }
</div>

WebUI/Views/Orders/Details.cshtml
@model Domain.ModelView.OrderV
@{
    ViewBag.Title = ViewBag.Order;
}
@section metatags
{
    <meta name="description" content="@ViewBag.Title" />
    <meta name="keywords" content="@ViewBag.Title, АБЗ-4" />
    <meta name="robots" content="noindex, nofollow">
}
@section Scripts 
    {
        @Scripts.Render("~/bundles/jqueryval")  
          @Styles.Render("~/Content/datetimepickercss")
        @Scripts.Render("~/bundles/datetimepickerjs")
    }
<div class="row">
    <div class="col-md-12">
        <section id="orderForm" class="client-form">
            @using (Html.BeginForm("Booking", "Orders", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <fieldset>
                    @Html.HiddenFor(model => model.Order.OrderId)
                </fieldset>
                <h2>Выберите дату</h2>

                <div class="form-group">
                    <div class="col-md-9">
                        @Html.TextBoxFor(m => m.Order.cDat, new { @class = "form-control datefield", @type = "text" })
                    </div>
                </div>

                <h2>Заказанные товары</h2>

                <p class="help-block">
                    <input name="Gd" type="submit" value="Добавить в заказ товар" class="actionButtons btn btn-xs-sm-md btn-default btn-success" role="button" title="Добавить в заказ еще товар" />
                </p>

                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-grey-header null-margin">
                        <thead>
                            <tr>
                                <th>
                                    Продукция
                                </th>
                                <th>
                                    Ед. изм.
                                </th>
                                <th>
                                    Количество
                                </th>
                                <th>
                                    Управление
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Prod)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(model => item.Good)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(model => item.Unit)
                                    </td>
                                    <td align="left">
                                            @Html.Hidden("ProductId", item.OrderProductId)
                                            <input type="number" name="qty" value="@item.Quant" size="2" width="100">
                                            <input class="actionButtons btn btn-xs-sm btn-success" type="submit" name="Recalc" value=" Пересчитать" title="Пересчитать товары в корзине" />
                                    </td>

                                    <td>
                                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe020;"), "DelProducts", new { id = item.OrderProductId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Удалить товар" })
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                @*<div class="form-group">
                    <label class="col-md-3 control-label">Доставка АБЗ</label>
                    <div class="col-md-9">
                        @Html.CheckBoxFor(model => model.Order.Centr, new { @class = "form-control checkbox" })
                        <p class="help-block">* Выберите способ доставки </p>
                    </div>

                    @Html.LabelFor(model => model.Order.Adres, htmlAttributes: new { @class = "col-md-3 control-label" })
                    <div class="col-md-9">*@
                        @*@Html.DropDownListFor(model => model.Order.AdresId, Model.SelectAdres, new { @class = "form-control" })*@
                        @*@Html.ValidationMessageFor(model => model.Order.Adres, "", new { @class = "text-danger" })
                        <p class="help-block">
                            <input name="Adr" type="submit" value="@HttpUtility.HtmlDecode("&#xe081;")" class="glyphicon actionButtons btn btn-xs-sm-md btn-default glyph-btn" role="button" title="Внести новый адрес" />
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            * Если вы хотите что бы доставку осуществил АБЗ-4
                            выберите из списка адрес доставки или внесите новый и установите галочку у способа доставки. Иначе снимите галочку со способа доставки.
                        </p>
                    </div>
                </div>
                <hr />*@
                <h2>Дополнительная информация к заказу</h2>
                <div class="form-group">
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.Order.Note, new { @class = "form-control multi-line", @rows = "3" })
                        @Html.ValidationMessageFor(model => model.Order.Note, "", new { @class = "text-danger" })
                        <p class="help-block">* тут вы можете указать удобное для вас время доставки продукции и другие ваши пожелания</p>
                    </div>
                </div>

                <div>
                    <hr />
                    @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к списку заказов", "Index", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к списку заказов" })
                    &nbsp;&nbsp;&nbsp;
                    <input type="submit" value="Сохранить заказ" class="actionButtons btn btn-xs-sm-md btn-success" />
                </div>
            }
        </section>
    </div>
</div>


<script type="text/javascript">
    $(function () {
        $('#Order_cDat').datetimepicker({
            locale: 'ru', format: 'DD.MM.YYYY'
        });
    });
</script>

WebUI/Views/Orders/GoodAdd.cshtml
@model Domain.Entities.OrderProductView

@{
    ViewBag.Title = "Количество товара";
}
<div class="row">
    <div class="col-md-12">
        <section id="orderForm" class="client-form">
            @using (Html.BeginForm("Producrs", "Orders", FormMethod.Post, new { @class = "form-horizontal", @role = "form", @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <fieldset>
                    @Html.HiddenFor(model => model.OrderId)
                    @Html.HiddenFor(model => model.OrderProductId)
                    @Html.HiddenFor(model => model.ProductId)
                </fieldset>
                <div class="form-group">
                    @Html.LabelFor(model => model.Good, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Good, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Good, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quant, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Quant, new { @class = "form-control numfield", @value = "123.45", @pattern = "\\d+(,\\d{0,3})?" })
                        @Html.ValidationMessageFor(model => model.Quant, "", new { @class = "text-danger" })
                        <p class="help-block"><font size="2" color="#aaa">дробная часть - через запятую</font></p>
                    </div>
                </div>
                <div>
                    <hr />
                    @Html.ActionLink(@HttpUtility.HtmlDecode("&laquo;") + " вернуться к списку заказов", "Index", null, new { @class = "btn btn-xs-sm-md btn-default", @role = "button", @title = "Вернуться к списку заказов" })
                    &nbsp;&nbsp;&nbsp;
                    <input type="submit" value="Сохранить" class="actionButtons btn btn-xs-sm-md btn-success" />
                </div>
            }
        </section>
    </div>
</div>

WebUI/Views/Orders/GoodSelect.cshtml
@model IEnumerable<Domain.ModelView.GoodSelect>

@{
    ViewBag.Title = "Order";
}

<table class="table">
    <tr>
        <th>
            Наименование продукции
        </th>
        <th>
           Ед. изм.
        </th>
        <th>
            Укжите количество
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.txt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Unit)
        </td>

        <td align="left">
            @using (Html.BeginForm("Details", "Orders"))
            {
                @Html.Hidden("ID", item.ID)
                <input type="number" name="qty" value="@item.Quant" size="2" width="100">
                <input class="actionButtons btn btn-xs-sm btn-success" type="submit" value=" Внести заказ" title="Занести товар в заказ" />
            }
        </td>

    </tr>
}

</table>

WebUI/Views/Orders/GoodSelection.cshtml
@model IEnumerable<Domain.Entities.Good>

@{
    ViewBag.Title = "GoodSelection";
}

<h2>GoodSelection</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Наименование продукции
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.txt, "GoodAdd", "Orders", new { id = item.ID }, null)
        </td>
    </tr>
}

</table>

WebUI/Views/Orders/Index.cshtml
@model IEnumerable<Domain.Entities.OrderView>

<p>
    @Html.ActionLink("Создать новый", "Create", null,
                new
                {
                    @class = "actionButtons btn btn-default btn-success",
                    @role = "button",
                    @title = "Создать новый"
                })
</p>
<table align="center" class="table table-hover table-bordered table-grey-header">
    <thead>
        <tr>
            @if (ViewBag.Title == "Заказы")
            {
                <th>
                    № Заказа
                </th>
            }
            <th>
                Дата
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Good)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qty)
            </th>
            <th>
               Состояние
            </th>
            <th>
               Примечание
            </th>
            <th>
                @*Управление*@
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @if (ViewBag.Title == "Заказы")
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.OrderId)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.cDat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Good)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Qty)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    @if (item.StatusId == 1)
                    {
                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe065;"), "Edit", new { id = item.OrderId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Редактировать заказ" })
                        @Html.ActionLink(HttpUtility.HtmlDecode("&#xe020;"), "Delete", new { id = item.OrderId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Удалить заказ" })
                    }
                    @Html.ActionLink(HttpUtility.HtmlDecode("&#xe224;"), "Copy", new { id = item.OrderId }, new { @class = "actionButtons btn btn-xs-sm-md btn-default glyphicon glyph-btn", @role = "button", @title = "Копировать заказ" })
                </td>
            </tr>
        }
    </tbody>
</table>