WebUI/Controllers/SreestrController.cs
using System;
using System.Web.Mvc;
using Domain.Engine;
using Domain.Entities;
using System.Collections.Generic;
using System.Linq;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class SreestrController : Controller
    {
        private AbzContext db = new AbzContext();
        [Authorize]
        public ActionResult Sale()
        {
            Mydate mydate = new Mydate();
            mydate.dat = DateTime.Today;
            mydate.Cdat = DateToString.CDat(mydate.dat);

            return View(mydate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sale(Mydate cdt)
        {
            return View(cdt);
        }

        public ActionResult SelDat(Mydate cdt)
        {
            if (cdt.Cdat == null)
            {
                cdt = new Mydate();
                cdt.dat = DateTime.Today;
                cdt.Cdat = DateToString.CDat(cdt.dat);

            }
            DateTime dd = StringToDate.Date(cdt.Cdat);
            List<SaleReestr> reestr = db.SaleReestrs.Where(s => s.Ddat == dd).ToList();
            decimal smr = reestr.Sum(n => n.Kol);
            string csm = smr.ToString();
            ViewBag.smr = "Итого за " + cdt.Cdat + " - " + csm;
            return PartialView(reestr);
        }
        [Authorize]
        public ActionResult Sup()
        {
            Mydate mydate = new Mydate();
            mydate.dat = DateTime.Today;
            mydate.Cdat = DateToString.CDat(mydate.dat);

            return View(mydate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sup(Mydate cdt)
        {
            return View(cdt);
        }
        public ActionResult SupDat(Mydate cdt)
        {
            if (cdt.Cdat == null)
            {
                cdt = new Mydate();
                cdt.dat = DateTime.Today;
                cdt.Cdat = DateToString.CDat(cdt.dat);

            }
            DateTime dd = StringToDate.Date(cdt.Cdat);
            List<SupReestr> reestr = db.SupReestrs.Where(s => s.Ddat == dd).ToList();                
            return PartialView(reestr);
        }

        public ActionResult MainMenu(string menuItem)
        {
            ViewBag.MenuItem = menuItem;
            return PartialView();
        }

    }
}

WebUI/Views/Shared/Delete.cshtml
@model WebUI.Models.TriesModel
@section metatags
{
    <meta name="robots" content="noindex, nofollow">
}
<form method="post">
    <fieldset>@Html.HiddenFor(m => m.CountTries)</fieldset>
    <div class="row">
        <div class="col-md-4">
            @if (ViewBag.ErrorMessage != null)
            {
                <p class="text-danger">@ViewBag.ErrorMessage</p>
            }
            <h2>Вы уверены?</h2>
            <hr />
            <div class="form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-xs-sm-md btn-success" role="button" title="Подтвердить удаление">
                        Удалить
                    </button>
                    <a href="@Model.ReturnUrl" role="button" class="btn btn-xs-sm-md btn-default pull-right" title="Возврат на предыдущую страницу">
                        Отмена
                    </a>
                </div>
            </div>
        </div>
    </div>
</form>

WebUI/Views/Shared/NoCust.cshtml
@{
    ViewBag.Title = "Нет контрагента";
}

<hgroup>
    @*<h1 class="text-danger">Заблокировано.</h1>*@
    <h2 class="text-danger">Эта учетная запись не привязана к контрагенту</h2>
</hgroup>

WebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @RenderSection("metatags", false)
    <meta name="author" content="K&K" />
    @*<title>@ViewBag.Title – ООО ЛАГОС</title>*@
    <title>@ViewBag.Title – ЛК</title>
    @Scripts.Render("~/bundles/fontloader")
    <link href="/images/favicon.ico" rel="shortcut icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/bundles/modernizr")
</head>
<body>
    <header class="hidden-print">
        <div class="top-menu-wrapper">
            <div class="container clearfix ">
                <div class="pull-right top-right">
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="navbar navbar-default navbar-static-top navbar-wrapper" role="navigation">
            <div class="container clearfix">
                <div class="navbar-header header-logo">
                    <button type="button" class="navbar-toggle btn-main-menu-xs" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    

                    @*<a class="navbar-brand logo-brand" href="/Home" title="Личный кабинет ООО 'ЛАГОС'">
                        <img src="/images/logo-account.png" width="415" height="55" alt="Личный кабинет ООО 'ЛАГОС'" title="Личный кабинет ООО 'ЛАГОС'">
                    </a>*@
                    

                </div>
            </div>
            @*@if (Request.IsAuthenticated)
            {@Html.RenderAction("MainMenu", "Sreestr")
            , new { menuItem = ViewBag.MenuItem })*@
            @if (Request.IsAuthenticated)
            { Html.RenderAction("MainMenu", "Sreestr", new { menuItem = ViewBag.MenuItem }); }


            @*@if (Request.IsAuthenticated)
            {
                Html.Partial("MainMenu");
            }*@
        </div>
    </header>
    @if (ViewBag.IsMainPage != null && ViewBag.IsMainPage)
    {
        <div class="container body-content content-wrapper">
            @RenderBody()
        </div>
    }
    else
    {
        if (!string.IsNullOrEmpty(ViewBag.ContentTitle))
        { <h1>@ViewBag.ContentTitle</h1> }
        <div class="container body-content content-wrapper">
            <div class="row">
                <div class="content-block col-md-12 @Html.Encode(ViewBag.MenuItem == "news" ? "null-padding" : "") ">
                    @RenderBody()
                </div>
            </div>
        </div>
    }
    @*<footer class="footer-wrapper hidden-print">
        @{ Html.RenderAction("FooterMenu", "Home"); }
        <div class="container-fluid footer-bottom-wrapper">
            <div class="container clearfix footer-bottom">
                <p class="footer-copyright-info">
                    &copy;&nbsp;@DateTime.Now.Year &nbsp;&nbsp;<span class="fn">ООО "ЛАГОС"</span>
                </p>
                <p class="pull-right back-to-top-wrap">
                    <a class="back-to-top" href="#top">
                        <span class="glyphicon glyphicon-chevron-up"></span>
                    </a>
                </p>
            </div>
        </div>
    </footer>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>